/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import static java.lang.Integer.parseInt;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.ShoppingCart;

/**
 *
 * @author Rasmus
 */
public class FinalBuyView extends javax.swing.JPanel {

    /**
     * Creates new form FinalBuyView
     */
    
    private static JPanel jp;
    private static IMatView imv;
    private static boolean ishomeDelivery;
    private IMatDataHandler im;
    private static boolean validInputs;
    
    public FinalBuyView(JPanel jpInput, IMatView imvInput) {
        initComponents();
        
      
        
        im = IMatDataHandler.getInstance();
        imv = imvInput;
        ShoppingCart SC = im.getShoppingCart();
        jp = jpInput;
        ishomeDelivery = true;
        homeDeliveryRadioButton.setSelected(true);
        validInputs = true;
        
        totalLabel.setText(totalLabel.getText()+ " " + (String.format("%.2f",SC.getTotal())) + " kr");
        
        
        File f = new File(im.imatDirectory() + "/saveCredit.txt");
        Scanner sc = null;
        try {
            sc = new Scanner(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignInView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String s = sc.nextLine();
        sc.close();
        
        if(imv.isLoggedIn){
        
            this.nameField.setText(im.getCustomer().getFirstName());
            this.LastNameField.setText(im.getCustomer().getLastName());
            this.addressField.setText(im.getCustomer().getAddress());
            this.zipCodeField.setText(im.getCustomer().getPostCode());
            this.cityField.setText(im.getCustomer().getPostAddress());
            this.emailField.setText(im.getUser().getUserName());
            this.phoneField.setText(im.getCustomer().getMobilePhoneNumber());
            if(im.getCreditCard().getCardNumber()!=null &&  s.equals("1")){
                String credNr = im.getCreditCard().getCardNumber();
                this.cardNrField1.setText(credNr.substring(0,4));
                this.cardNrField2.setText(credNr.substring(4,8));
                this.cardNrField3.setText(credNr.substring(8,12));
                this.cardNrField4.setText(credNr.substring(12));
                
            }
            
            if(s.equals("1")){
            
                jCheckBox1.setSelected(true);
            
            }
            
        
        }
        
        for(int i = 1; i <= 31; i++){
           
            if(i<=12){
                
                validMComboBox.addItem(i+"");
            }
            //deliveryFComboBox;
            //deliveryTComboBox;
            if(14<i && i<31){
                validYComboBox.addItem(i+"");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cardNrField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CVCField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        homeDeliveryRadioButton = new javax.swing.JRadioButton();
        pickupDeliveryRadioButton = new javax.swing.JRadioButton();
        SMSBox = new javax.swing.JCheckBox();
        deliveryDComboBox = new javax.swing.JComboBox();
        deliveryFComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        OrderButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        validMComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        validYComboBox = new javax.swing.JComboBox();
        cardNrField4 = new javax.swing.JTextField();
        cardNrField2 = new javax.swing.JTextField();
        cardNrField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cardVerLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Förnamn:");

        jLabel2.setText("Efternamn:");

        jLabel3.setText("Address:");

        jLabel4.setText("Post nr:");

        zipCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeFieldActionPerformed(evt);
            }
        });
        zipCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zipCodeFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("Stad:");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Email:");

        jLabel7.setText("Mobil:");

        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
        });

        jLabel8.setText("Kort nr:");

        cardNrField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNrField1ActionPerformed(evt);
            }
        });
        cardNrField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNrFieldKeyTyped(evt);
            }
        });

        jLabel9.setText("CVC:");

        CVCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVCFieldActionPerformed(evt);
            }
        });
        CVCField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CVCFieldKeyTyped(evt);
            }
        });

        homeDeliveryRadioButton.setText("HemKörning");
        homeDeliveryRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                homeDeliveryRadioButtonStateChanged(evt);
            }
        });
        homeDeliveryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeDeliveryRadioButtonActionPerformed(evt);
            }
        });

        pickupDeliveryRadioButton.setText("Hämta i butik");
        pickupDeliveryRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pickupDeliveryRadioButtonStateChanged(evt);
            }
        });
        pickupDeliveryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupDeliveryRadioButtonActionPerformed(evt);
            }
        });

        SMSBox.setText("SMS Anvisering");

        deliveryDComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Imorgon", "2 dagar", "3 dagar", "4 dagar", "5dagar" }));

        deliveryFComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tid på dygnet...", "10:00-12:00", "12:00-14:00", "16:00-18:00", "18:00-20:00", "20:00-22:00" }));

        OrderButton.setBackground(Constants.NICE_GREEN
        );
        OrderButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(255, 255, 255));
        OrderButton.setText("Slutför köp");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        totalLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLabel.setText("Totalt:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));

        jCheckBox1.setText("Spara kontouppgifter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickupDeliveryRadioButton)
                            .addComponent(homeDeliveryRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deliveryFComboBox, 0, 113, Short.MAX_VALUE)
                            .addComponent(deliveryDComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SMSBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeDeliveryRadioButton)
                            .addComponent(deliveryDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pickupDeliveryRadioButton)
                            .addComponent(deliveryFComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SMSBox)
                            .addComponent(jLabel17)
                            .addComponent(jCheckBox1))))
                .addContainerGap())
        );

        jLabel10.setText("Varar:");

        validMComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
        validMComboBox.setName("Månad"); // NOI18N

        jLabel11.setText("/");

        validYComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
        validYComboBox.setToolTipText("");

        cardNrField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNrField4ActionPerformed(evt);
            }
        });
        cardNrField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNrFieldKeyTyped(evt);
            }
        });

        cardNrField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNrField2ActionPerformed(evt);
            }
        });
        cardNrField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNrFieldKeyTyped(evt);
            }
        });

        cardNrField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNrField3ActionPerformed(evt);
            }
        });
        cardNrField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNrFieldKeyTyped(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(validMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(cardNrField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cardNrField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validYComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardNrField3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CVCField, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(cardNrField4))
                                .addGap(18, 18, 18)
                                .addComponent(cardVerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cityField))
                                    .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(phoneField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cardNrField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNrField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNrField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNrField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CVCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(validMComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(validYComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cardVerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
         this.jLabel13.setText("");
          this.jLabel14.setText("");
           this.jLabel15.setText("");
            
            this.cardVerLabel.setText("");
           
          
        validInputs();
        if((this.jLabel13.getText() + this.jLabel14.getText()+ this.jLabel15.getText()).length()<1 && !this.cardVerLabel.getForeground().equals(Color.red)){
            
            if(jCheckBox1.isSelected()){
                im.getCreditCard().setCardNumber(cardNrField1.getText()+cardNrField2.getText()+ cardNrField3.getText()+ cardNrField4.getText());
                im.getCreditCard().setValidMonth(parseInt(validMComboBox.getSelectedItem().toString()));
                im.getCreditCard().setValidMonth(parseInt(validMComboBox.getSelectedItem().toString()));
            }
            
             File f = new File(im.imatDirectory() + "/saveCredit.txt");
                PrintWriter pw = null;
                try {
                    pw = new PrintWriter(f);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(FinalBuyView.class.getName()).log(Level.SEVERE, null, ex);
                }

                pw.print(boolToInt(jCheckBox1.isSelected()) + "");
                pw.close();
            
            //im.placeOrder(false);
            //im.shutDown();

            jp.removeAll();
            jp.revalidate();
            jp.repaint();
            String s = "";
            if(ishomeDelivery){
                s = "Hemkörning";
            }else{
                s = "Hämtas";
            }
            String time = this.deliveryFComboBox.getSelectedItem().toString();
            String day = this.deliveryDComboBox.getSelectedItem().toString();
            jp.add(new orderNotification(imv, nameField.getText(),LastNameField.getText(),addressField.getText(), time, day,s));
            im.placeOrder(true);
            im.shutDown();
            imv.updateKundVagn();
        }
        validInputs = true;
    }//GEN-LAST:event_OrderButtonActionPerformed
    
    private static int boolToInt(boolean b){
        if(b){
        return 1;
        }
        return 0;
    }
    
    private void validInputs(){
        
        int w = 100;
        if(!isValid(this.nameField.getText()) || !isValid(this.LastNameField.getText())){
             this.jLabel13.setText(String.format("<html><div style=\"width:%dpx;\">%s</div><html>", w,"Du måste fylla i hela ditt namn"));
            //this.jLabel13.setText("<html>"+"Du måste fylla i"+"<br>" +"hela ditt namn"+"</html>");
        }
        
        if(!isValid(this.addressField.getText()) || !isValid(this.zipCodeField.getText()) && !isValid(this.cityField.getText())){
            //this.jLabel14.setText("<html>"+"Kolla så du har fyllt i"+"<br>" +" din adress rätt"+"</html>");
             this.jLabel14.setText(String.format("<html><div style=\"width:%dpx;\">%s</div><html>", w,"Kolla så du har fyllt i din adress rätt"));
        }
        
        if(!isValid(this.phoneField.getText()) || !isValid(this.emailField.getText())){
            //this.jLabel15.setText("<html>"+"Din Email eller telefonr"+"<br>" +" är inte ifyllt"+"</html>");
             this.jLabel15.setText(String.format("<html><div style=\"width:%dpx;\">%s</div><html>", w,"Din email eller telefonr är inte ifyllt"));
        }
        
        if(!isValid(this.CVCField.getText()) || ((this.cardNrField1.getText() + this.cardNrField2.getText() + this.cardNrField3.getText() + this.cardNrField4.getText()).length() < 16) || this.validMComboBox.getSelectedItem().toString().equals( "---" ) || this.validYComboBox.getSelectedItem().toString().equals("---")  ){
            //this.jLabel16.setText("<html>"+"Du har inte fyllt i alla "+"<br>" +"  dina kontouppgiter"+"</html>");
            this.cardVerLabel.setForeground(Color.red);
            this.cardVerLabel.setText(String.format("<html><div style=\"width:%dpx;\">%s</div><html>", w,"Du har inte fyllt i alla dina kontouppgiter"));
        }
               
                
    }
    
    private static boolean isValid(String input){
        if(input.equals("")){
            validInputs = false;
            return false;
        }
        return true;
    }
    
    private void zipCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void cardNrField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNrField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNrField1ActionPerformed

    private void cardNrField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNrField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNrField4ActionPerformed

    private void cardNrField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNrField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNrField2ActionPerformed

    private void cardNrField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNrField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNrField3ActionPerformed

    private void CVCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVCFieldActionPerformed

    private void homeDeliveryRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_homeDeliveryRadioButtonStateChanged
        // TODO add your handling code here:
        //System.out.println(homeDeliveryRadioButton.getText());
        
        //pickupDeliveryRadioButton.
    }//GEN-LAST:event_homeDeliveryRadioButtonStateChanged

    private void pickupDeliveryRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pickupDeliveryRadioButtonStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pickupDeliveryRadioButtonStateChanged

    private void homeDeliveryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeDeliveryRadioButtonActionPerformed
        // TODO add your handling code here:
        pickupDeliveryRadioButton.setSelected(false);
        
        ishomeDelivery = true;
    }//GEN-LAST:event_homeDeliveryRadioButtonActionPerformed

    private void pickupDeliveryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupDeliveryRadioButtonActionPerformed
        // TODO add your handling code here:
        homeDeliveryRadioButton.setSelected(false);
        ishomeDelivery = false;
    }//GEN-LAST:event_pickupDeliveryRadioButtonActionPerformed

    private void cardNrFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNrFieldKeyTyped
        // TODO add your handling code here:
        
       JTextField tf = (JTextField)evt.getComponent();
       
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE) ||  tf.getText().length()>3){
            evt.consume();
        }
        
        String s = cardNrField1.getText();
        if(isOnlyFour(cardNrField1)){
        s = s.substring(0, 1);
        System.out.println("String: " + s);
        if(s.equals("4")){
            this.cardVerLabel.setForeground(Color.black);
            cardVerLabel.setText("Visa");
        }else if(s.equals("5")){
            this.cardVerLabel.setForeground(Color.black);
            cardVerLabel.setText("Master Card");
        }else{
            cardVerLabel.setText("");
        }
        }
        
        if(isOnlyFour(cardNrField4)){
         
        }else if(isOnlyFour(cardNrField3)){
            cardNrField4.requestFocusInWindow();
        }else if(isOnlyFour(cardNrField2)){
            cardNrField3.requestFocusInWindow();
        }else if(isOnlyFour(cardNrField1)){
            cardNrField2.requestFocusInWindow();
        }
        
        
    }//GEN-LAST:event_cardNrFieldKeyTyped

    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyTyped
        // TODO add your handling code here:
        JTextField tf = (JTextField)evt.getComponent();
       
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_phoneFieldKeyTyped

    private void CVCFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CVCFieldKeyTyped
        // TODO add your handling code here:
        JTextField tf = (JTextField)evt.getComponent();
       
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE) ||  tf.getText().length()>2){
            evt.consume();
        }
    }//GEN-LAST:event_CVCFieldKeyTyped

    private void zipCodeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipCodeFieldKeyTyped
        // TODO add your handling code here:
        JTextField tf = (JTextField)evt.getComponent();
       
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE) ||  tf.getText().length()>4){
            evt.consume();
        }
    }//GEN-LAST:event_zipCodeFieldKeyTyped
    
    private boolean isOnlyFour(JTextField jtf){
       if(jtf.getText().length()>2){
           return true;
       }
       return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVCField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JButton OrderButton;
    private javax.swing.JCheckBox SMSBox;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField cardNrField1;
    private javax.swing.JTextField cardNrField2;
    private javax.swing.JTextField cardNrField3;
    private javax.swing.JTextField cardNrField4;
    private javax.swing.JLabel cardVerLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JComboBox deliveryDComboBox;
    private javax.swing.JComboBox deliveryFComboBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton homeDeliveryRadioButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JRadioButton pickupDeliveryRadioButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JComboBox validMComboBox;
    private javax.swing.JComboBox validYComboBox;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
