/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Lasse
 */
public class ListorPanel extends javax.swing.JPanel {
    List<ShoppingItem> list = new ArrayList<ShoppingItem>();
    
    IMatView view;
    
    Map<String,String> map;
    
    IMatDataHandler dh = IMatDataHandler.getInstance();
    DefaultListModel<String> listModel;
    /**
     * Creates new form listorPanel
     */
    public ListorPanel(IMatView view) {
        this.view = view;
        initComponents();
        update();
        
        Utils.changeScrollBar(jScrollPane1, 11);
        
        
        Utils.changeScrollBar(jScrollPane2, 13);
        
        jScrollPane2.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {

            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                System.out.println("hehjhejhejhej");
                if(jScrollPane2.getVerticalScrollBar().isShowing()){
                    jScrollPane2.setBorder(BorderFactory.createLineBorder(Color.gray));
                    jPanel1.setBorder(BorderFactory.createEmptyBorder());
                } else {
                    jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
                    jPanel1.setBorder(BorderFactory.createLineBorder(Color.gray));
                }
                    
            }
        });
        
    }
    
    public void update(){
        
        map = new TreeMap<String,String>();
        
        int index = jList1.getSelectedIndex();
        if(index == -1){
            index = 0;
        }
        
        listModel = new DefaultListModel<String>();
        
        File folder = new File(dh.imatDirectory() + "/inköpslistor");
        
        File[] listOfFiles = folder.listFiles();
        
        if(listOfFiles.length == 0){
            jPanel1.removeAll();
            jPanel1.revalidate();
            jPanel1.repaint();
            
            jLabel3.setText("Totalt: ");
            jLabel2.setText("");
        }
        
        Scanner sc = null;
        for(File f : listOfFiles){
            try {
                sc = new Scanner(f);
            } catch (FileNotFoundException ex) {
                System.out.println("catch block");
                Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            String listName = sc.nextLine().split(";")[0];
            sc.close();
            listModel.addElement(listName);
            map.put(listName, f.getName());
        }
        
        
        jList1.setModel(listModel);
        jList1.setSelectedIndex(index);
        //this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listor");

        jButton2.setText("ta bort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ny");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        add(jPanel2);

        jScrollPane2.setBorder(null);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        //jPanel1.setLayout(new ModifiedFlowLayout(FlowLayout.CENTER, 2, 2));
        jPanel1.setLayout(new java.awt.GridLayout());
        jPanel4.add(jPanel1);
        jPanel4.add(filler1);
        jPanel4.add(filler2);
        jPanel4.add(filler7);
        jPanel4.add(filler6);
        jPanel4.add(filler5);
        jPanel4.add(filler4);
        jPanel4.add(filler3);

        jScrollPane2.setViewportView(jPanel4);

        jLabel2.setText("jLabel2");

        jButton1.setText("Lägg Till");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(jList1.getSelectedIndex() == -1){
            return;
        }
        if (!evt.getValueIsAdjusting()) {//This line prevents double events
            String s = (String) jList1.getSelectedValue();
            
            
            updateVarorList(s);

        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
    
    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        
    }//GEN-LAST:event_jList1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s = (String) jList1.getSelectedValue();
        File f = new File(dh.imatDirectory() + "/inköpslistor/" + map.get(s));
        
        System.out.println(f.getName());
        
        
        if(f.delete()){
            System.out.println("list was deleted successfully");
            
        } else {
            System.out.println("failed deletion");
        }
        
        jList1.setSelectedIndex(jList1.getSelectedIndex()-1);
        
        this.update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(ShoppingItem si : list){
            view.addToKundVagn(si.getProduct(), si.getAmount());
        }
        view.updateKundVagn();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s;
        
        while(true){
            s = JOptionPane.showInputDialog("namn på listan?");
            
            if(s == null){
                return;
            }
            
            if(s.contains(";")){
                JOptionPane.showMessageDialog(this, "semikolon ej tillåtet");
                
            } else {
                break;
            }
        }
        
        
        Utils.createEmptyList(s);
        
        update();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void updateVarorList(final String s) {
        jLabel2.setText(s);
        
        list.clear();
        
        
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        
        Double totalPrice = 0.0;
        
        File f = new File(dh.imatDirectory() + "/inköpslistor/" + map.get(s));
        
        String fileContent = "";
        Scanner sc;
        if(f.exists()){
            
            sc = null;
            try {
                sc = new Scanner(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(sc.hasNextLine()){
                fileContent = sc.nextLine();
            } else {
                return;
            }
        } else {
            return;
            
        }
        
        sc.close();
        
        String [] arr = fileContent.split(";");
        jPanel1.setLayout(new GridLayout(arr.length-1, 1));
        
        int counter = 0;
        for(String x : arr){
            counter ++;
            final int c = counter; // for listeners
            
            if(counter == 1){
                continue;
            }
            String[] y = x.split(":");
            
            
            ShoppingItem si = new ShoppingItem(dh.getProduct(Integer.parseInt(y[0])), Double.parseDouble(y[1]));
            list.add(si);
            
            
            totalPrice += si.getProduct().getPrice() * si.getAmount();
            
            //jPanel1.add(new JLabel("hej"));
            ProductInList pil = new ProductInList(si);
            //pil.setPreferredSize(new Dimension(280,30));
            pil.getButton().addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Scanner sc = null;
                    try {
                        sc = new Scanner(f);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    String newString = "";
                    
                    String ss = sc.nextLine();
                    String[] arr = ss.split(";");
                    
                    for(int i = 0; i < arr.length; i ++){
                        if(i != c-1){
                            newString += arr[i] + ";";
                        }
                        
                    }
                    
                    sc.close();
                    PrintWriter pw = null;
                    try {
                        pw = new PrintWriter(f);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    pw.print(newString);
                    pw.close();
                    
                    updateVarorList(s);
                    
                }
            });
            
            pil.getplusButton().addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Scanner sc = null;
                    try {
                        sc = new Scanner(f);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    String newString = "";
                    
                    String ss = sc.nextLine();
                    String[] arr = ss.split(";");
                    
                    for(int i = 0; i < arr.length; i ++){
                        if(i == c-1){
                            String aShoppingItem = arr[i];
                            String[] xx = aShoppingItem.split(":");
                            
                            Double newAmount = Double.parseDouble(xx[1]);
                            if(pil.isKgItem()){
                                newAmount += 0.2;
                            } else {
                                newAmount += 1;
                            }
                            
                            newString += xx[0] + ":" + newAmount + ";";
                        } else {
                            newString += arr[i] + ";";
                        }
                        
                        
                    }
                    
                    sc.close();
                    PrintWriter pw = null;
                    try {
                        pw = new PrintWriter(f);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    pw.print(newString);
                    pw.close();
                    
                    updateVarorList(s);
                }
            });
            
            pil.getminusButton().addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Scanner sc = null;
                    try {
                        sc = new Scanner(f);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    String newString = "";
                    
                    String ss = sc.nextLine();
                    String[] arr = ss.split(";");
                    
                    for(int i = 0; i < arr.length; i ++){
                        if(i == c-1){
                            String aShoppingItem = arr[i];
                            String[] xx = aShoppingItem.split(":");
                            
                            Double newAmount = Double.parseDouble(xx[1]);
                            if(pil.isKgItem()){
                                newAmount = Math.max(0, newAmount-0.2);
                            } else {
                                newAmount = Math.max(0, newAmount-1);
                            }
                            
                            newString += xx[0] + ":" + newAmount + ";";
                        } else {
                            newString += arr[i] + ";";
                        }
                        
                        
                    }
                    
                    sc.close();
                    PrintWriter pw = null;
                    try {
                        pw = new PrintWriter(f);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ListorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    pw.print(newString);
                    pw.close();
                    
                    updateVarorList(s);
                }
            });
            
            jPanel1.add(pil);
        }
        
        jLabel3.setText("Totalt: " + String.format("%.2f", totalPrice) + " kr");
        
        
        
        
        
        
        
        
        
        
        
        this.repaint();
        
    }
}
