/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import javax.swing.JButton;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Lasse
 */
public class ProductInList extends javax.swing.JPanel {
    
    ShoppingItem si;
    /**
     * Creates new form ProductInList
     */
    public ProductInList(ShoppingItem si) {
        this.si = si;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setText("" + (int)si.getAmount());
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 25, 24));

        jLabel1.setText(si.getProduct().getName());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 3, 140, 24));

        jButton1.setText("X");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 5, 40, 20));
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    public JButton getButton(){
        return jButton1;
    }
}
