/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author Lasse
 */
public class ProductSummaryView extends javax.swing.JPanel {
    IMatDataHandler dh = IMatDataHandler.getInstance();
    
    private Product p;
    private int amountToBuy = 1;
    /**
     * Creates new form ProductSummaryView
     */
    public ProductSummaryView(Product p) {
        this.p = p;
        initComponents();
        favoriteButton.setVisible(false);
        listButton.setVisible(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        favoriteButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //System.out.println(jLabel1.getHeight());
        jLabel1.setIcon(dh.getImageIcon(p, 140, 100));
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, 137, 90));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText(p.getName());
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 114, 102, 22));

        jLabel3.setText("" + p.getPrice() + " " + p.getUnit());
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 146, 63, -1));

        jButton1.setText("Köp");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 185, -1, -1));

        jSpinner1.setValue(1);
        jSpinner1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSpinner1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSpinner1MouseEntered(evt);
            }
        });
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, -1, -1));

        favoriteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/bilder/ofylltHjärta.png"))); // NOI18N
        favoriteButton.setText("jButton2");
        favoriteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        favoriteButton.setBorderPainted(false);
        favoriteButton.setContentAreaFilled(false);
        favoriteButton.setFocusPainted(false);
        favoriteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favoriteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favoriteButtonMouseExited(evt);
            }
        });
        favoriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteButtonActionPerformed(evt);
            }
        });
        add(favoriteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 111, 30, 28));

        listButton.setText("jButton2");
        listButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listButton.setBorderPainted(false);
        listButton.setContentAreaFilled(false);
        listButton.setFocusPainted(false);
        listButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listButtonMouseExited(evt);
            }
        });
        add(listButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 146, 30, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinner1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinner1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1AncestorAdded

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        
// TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void favoriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteButtonActionPerformed
       if(!filled){
           File sourceimage = new File("src\\imat\\resources\\bilder\\fylltHjärta.png");
        try {
            Image image = ImageIO.read(sourceimage);
            favoriteButton.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(ProductSummaryView.class.getName()).log(Level.SEVERE, null, ex);
        }
        filled = true;
       }
       else{
        File sourceimage = new File("src\\imat\\resources\\bilder\\ofylltHjärta.png");
        try {
            Image image = ImageIO.read(sourceimage);
            favoriteButton.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(ProductSummaryView.class.getName()).log(Level.SEVERE, null, ex);
        }
        filled = false;
       }
        
// TODO add your handling code here:
    }//GEN-LAST:event_favoriteButtonActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        showFavoriteAndListButtons();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        hideFavoriteAndListButtons();
    }//GEN-LAST:event_formMouseExited

    private void favoriteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteButtonMouseEntered
        showFavoriteAndListButtons();
    }//GEN-LAST:event_favoriteButtonMouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        showFavoriteAndListButtons();
    }//GEN-LAST:event_jButton1MouseEntered

    private void jSpinner1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseEntered
        showFavoriteAndListButtons();
    }//GEN-LAST:event_jSpinner1MouseEntered

    private void listButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listButtonMouseEntered
        showFavoriteAndListButtons();
    }//GEN-LAST:event_listButtonMouseEntered

    private void favoriteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteButtonMouseExited
        hideFavoriteAndListButtons();
    }//GEN-LAST:event_favoriteButtonMouseExited

    private void listButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listButtonMouseExited
        hideFavoriteAndListButtons();
    }//GEN-LAST:event_listButtonMouseExited

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        hideFavoriteAndListButtons();
        }//GEN-LAST:event_jButton1MouseExited

    
    
    public JButton getButton(){
        return jButton1;
    }
    public int getAmount(){
        return (int) jSpinner1.getValue();
         }
    public void resetAmount(){
        jSpinner1.setValue(1);
         }
    public void showFavoriteAndListButtons(){
        listButton.setVisible(true);
        favoriteButton.setVisible(true);
    }
    protected void hideFavoriteAndListButtons(){
        listButton.setVisible(false);
        favoriteButton.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton favoriteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton listButton;
    // End of variables declaration//GEN-END:variables
    private boolean filled = false;
}
