/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Button;
import javax.swing.JButton;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author jesper
 */
public class ProductInRecipeList extends javax.swing.JPanel {

    ShoppingItem si;

    /**
     * Creates new form ProductInRecipeList
     */
    public ProductInRecipeList(ShoppingItem si) {
        this.si = si;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("X");
        deleteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteButton.setBorderPainted(false);
        deleteButton.setContentAreaFilled(false);
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 40, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(String.format( "%.2f", si.getProduct().getPrice()*si.getAmount()) + " kr");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 70, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(si.getProduct().getName());
        jLabel1.setToolTipText(si.getProduct().getName());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 30));

        jTextField2.setText(String.format("%.2f", si.getAmount()) + " " + si.getProduct().getUnitSuffix());
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

 public JButton getDeleteButton(){
        return deleteButton;
    }
 public boolean isKgItem(){
        if (si.getProduct().getUnit().equals("kr/kg")) {
            return true;
        } else {
            return false;
        }
    } 
}



